/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#006d2f',
          50: '#e6f5eb',
          100: '#ccebd6',
          200: '#99d7ad',
          300: '#66c384',
          400: '#33af5b',
          500: '#006d2f',
          600: '#005726',
          700: '#00411e',
          800: '#002b15',
          900: '#00150b',
        },
        'primary-container': '#25d366',
        'on-primary': '#ffffff',
        'on-primary-container': '#005523',
        secondary: '#1c695f',
        'secondary-container': '#a5ede0',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#226e63',
        tertiary: '#93492e',
        'tertiary-container': '#ffa07e',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#78351b',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f7f9fc',
        surface: '#f7f9fc',
        'surface-dim': '#d8dadd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'surface-container-high': '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'surface-variant': '#e0e3e6',
        'surface-tint': '#006d2f',
        'on-surface': '#191c1e',
        'on-surface-variant': '#3c4a3d',
        'on-background': '#191c1e',
        outline: '#6c7b6b',
        'outline-variant': '#bbcbb9',
        inverse: {
          surface: '#2d3133',
          'on-surface': '#eff1f4',
          primary: '#3de273',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.06)',
        'glass-lg': '0 -8px 32px rgba(0, 0, 0, 0.06)',
      },
    },
  },
  plugins: [],
}
