/** @type {import('tailwindcss').Config} */
const c = (name) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: c('color-primary'),
          50: c('color-primary-50'),
          100: c('color-primary-100'),
          200: c('color-primary-200'),
          300: c('color-primary-300'),
          400: c('color-primary-400'),
          500: c('color-primary-500'),
          600: c('color-primary-600'),
          700: c('color-primary-700'),
          800: c('color-primary-800'),
          900: c('color-primary-900'),
        },
        'primary-container': c('color-primary-container'),
        'on-primary': c('color-on-primary'),
        'on-primary-container': c('color-on-primary-container'),
        secondary: c('color-secondary'),
        'secondary-container': c('color-secondary-container'),
        'on-secondary': c('color-on-secondary'),
        'on-secondary-container': c('color-on-secondary-container'),
        tertiary: c('color-tertiary'),
        'tertiary-container': c('color-tertiary-container'),
        'on-tertiary': c('color-on-tertiary'),
        'on-tertiary-container': c('color-on-tertiary-container'),
        error: c('color-error'),
        'error-container': c('color-error-container'),
        'on-error': c('color-on-error'),
        'on-error-container': c('color-on-error-container'),
        background: c('color-background'),
        surface: c('color-surface'),
        'surface-dim': c('color-surface-dim'),
        'surface-container-lowest': c('color-surface-container-lowest'),
        'surface-container-low': c('color-surface-container-low'),
        'surface-container': c('color-surface-container'),
        'surface-container-high': c('color-surface-container-high'),
        'surface-container-highest': c('color-surface-container-highest'),
        'surface-variant': c('color-surface-variant'),
        'surface-tint': c('color-surface-tint'),
        'on-surface': c('color-on-surface'),
        'on-surface-variant': c('color-on-surface-variant'),
        'on-background': c('color-on-background'),
        outline: c('color-outline'),
        'outline-variant': c('color-outline-variant'),
        inverse: {
          surface: c('color-inverse-surface'),
          'on-surface': c('color-inverse-on-surface'),
          primary: c('color-inverse-primary'),
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.06)',
        'glass-lg': '0 -8px 32px rgba(0, 0, 0, 0.06)',
      },
    },
  },
  plugins: [],
};
